// Standard CSS Color Module Level 4 named colors (real, published keyword
// list — not invented). Used for "nearest named color" lookups since we
// don't have licensed Pantone matching data to draw from honestly.
export const NAMED_COLORS: { name: string; hex: string }[] = [
  { name: "Black", hex: "#000000" }, { name: "Dim Gray", hex: "#696969" },
  { name: "Gray", hex: "#808080" }, { name: "Dark Gray", hex: "#A9A9A9" },
  { name: "Silver", hex: "#C0C0C0" }, { name: "Light Gray", hex: "#D3D3D3" },
  { name: "Gainsboro", hex: "#DCDCDC" }, { name: "White Smoke", hex: "#F5F5F5" },
  { name: "White", hex: "#FFFFFF" }, { name: "Maroon", hex: "#800000" },
  { name: "Dark Red", hex: "#8B0000" }, { name: "Firebrick", hex: "#B22222" },
  { name: "Crimson", hex: "#DC143C" }, { name: "Red", hex: "#FF0000" },
  { name: "Tomato", hex: "#FF6347" }, { name: "Coral", hex: "#FF7F50" },
  { name: "Indian Red", hex: "#CD5C5C" }, { name: "Salmon", hex: "#FA8072" },
  { name: "Dark Salmon", hex: "#E9967A" }, { name: "Light Salmon", hex: "#FFA07A" },
  { name: "Orange Red", hex: "#FF4500" }, { name: "Dark Orange", hex: "#FF8C00" },
  { name: "Orange", hex: "#FFA500" }, { name: "Gold", hex: "#FFD700" },
  { name: "Dark Goldenrod", hex: "#B8860B" }, { name: "Goldenrod", hex: "#DAA520" },
  { name: "Saddle Brown", hex: "#8B4513" }, { name: "Sienna", hex: "#A0522D" },
  { name: "Chocolate", hex: "#D2691E" }, { name: "Peru", hex: "#CD853F" },
  { name: "Sandy Brown", hex: "#F4A460" }, { name: "Burlywood", hex: "#DEB887" },
  { name: "Tan", hex: "#D2B48C" }, { name: "Wheat", hex: "#F5DEB3" },
  { name: "Yellow", hex: "#FFFF00" }, { name: "Khaki", hex: "#F0E68C" },
  { name: "Dark Khaki", hex: "#BDB76B" }, { name: "Olive", hex: "#808000" },
  { name: "Yellow Green", hex: "#9ACD32" }, { name: "Dark Olive Green", hex: "#556B2F" },
  { name: "Olive Drab", hex: "#6B8E23" }, { name: "Lawn Green", hex: "#7CFC00" },
  { name: "Chartreuse", hex: "#7FFF00" }, { name: "Green Yellow", hex: "#ADFF2F" },
  { name: "Dark Green", hex: "#006400" }, { name: "Green", hex: "#008000" },
  { name: "Forest Green", hex: "#228B22" }, { name: "Lime", hex: "#00FF00" },
  { name: "Lime Green", hex: "#32CD32" }, { name: "Light Green", hex: "#90EE90" },
  { name: "Pale Green", hex: "#98FB98" }, { name: "Sea Green", hex: "#2E8B57" },
  { name: "Medium Sea Green", hex: "#3CB371" }, { name: "Spring Green", hex: "#00FF7F" },
  { name: "Emerald", hex: "#10B981" }, { name: "Teal", hex: "#008080" },
  { name: "Dark Cyan", hex: "#008B8B" }, { name: "Light Sea Green", hex: "#20B2AA" },
  { name: "Cyan", hex: "#00FFFF" }, { name: "Turquoise", hex: "#40E0D0" },
  { name: "Medium Turquoise", hex: "#48D1CC" }, { name: "Cadet Blue", hex: "#5F9EA0" },
  { name: "Steel Blue", hex: "#4682B4" }, { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Light Sky Blue", hex: "#87CEFA" }, { name: "Deep Sky Blue", hex: "#00BFFF" },
  { name: "Dodger Blue", hex: "#1E90FF" }, { name: "Cornflower Blue", hex: "#6495ED" },
  { name: "Royal Blue", hex: "#4169E1" }, { name: "Blue", hex: "#0000FF" },
  { name: "Medium Blue", hex: "#0000CD" }, { name: "Navy", hex: "#000080" },
  { name: "Midnight Blue", hex: "#191970" }, { name: "Slate Blue", hex: "#6A5ACD" },
  { name: "Medium Slate Blue", hex: "#7B68EE" }, { name: "Indigo", hex: "#4B0082" },
  { name: "Dark Violet", hex: "#9400D3" }, { name: "Dark Orchid", hex: "#9932CC" },
  { name: "Purple", hex: "#800080" }, { name: "Medium Purple", hex: "#9370DB" },
  { name: "Amethyst", hex: "#8B5CF6" }, { name: "Blue Violet", hex: "#8A2BE2" },
  { name: "Violet", hex: "#EE82EE" }, { name: "Plum", hex: "#DDA0DD" },
  { name: "Orchid", hex: "#DA70D6" }, { name: "Magenta", hex: "#FF00FF" },
  { name: "Medium Violet Red", hex: "#C71585" }, { name: "Deep Pink", hex: "#FF1493" },
  { name: "Hot Pink", hex: "#FF69B4" }, { name: "Pale Violet Red", hex: "#DB7093" },
  { name: "Pink", hex: "#FFC0CB" }, { name: "Light Pink", hex: "#FFB6C1" },
  { name: "Rosy Brown", hex: "#BC8F8F" }, { name: "Slate Gray", hex: "#708090" },
];
